### ISSUE TITLE
If-statement rewriting leading to broken AST?

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/ABC#11]
I suspect that the If-statement rewriting will break the AST if certain non-rewriteable statements are in the Then- or Else-branch, for example, a For-loop.

A test must be added to verify or falsify the `CompileTimeExpressionSimplifier`'s result if an If-statement includes a For-loop.

**Comment by AlexanderViand** [comment]
The new SecretBranchingVisitor in v2.0 addresses this, as verified by [`TEST(SecretBranchingVisitorTest, secretVariable_ifBranch_unsupportedBodyFor_noRewritingExpected)`](https://github.com/MarbleHE/ABC/blob/eb4052999a6329867bba2a71b535a91f08f7e626/test/visitor/SecretBranchingVisitorTest.cpp#L235-L261)
