### ISSUE TITLE
 Add scope support to ControlFlowGraphVisitor

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/ABC#13]
The ControlFlowGraphVisitor currently uses a variable's identifier only to distinguish between variables. This, however, does not uniquely identify a variable because there can be multiple variables with the same identifier, declared in different scopes. We therefore need to also take the scope into account.

This enhancement is already implemented in the CompileTimeExpressionSimplifier and uses scope information provided by the base Visitor class.

**Comment by AlexanderViand** [comment]
The new CFGV implementation has support for Scopes
