### ISSUE TITLE
Add matrix access tracking to ControlFlowGraphVisitor

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/ABC#14]
The `ControlFlowGraphVisitor` currently uses a `std::vector<std::string>` to store the variable that are accessed (read or written). This, however, is not enough as there might exists multiple variables with the same identifier but declared in different scopes. See #13 that addresses this issue.

In addition to the missing scope support, it would be useful to allow tracking of matrix accesses. As a current and very rudimentary workaround, a string like "Variable(M)[LiteralInt(21)][LiteralInt(3)]" is constructed and used. As we cannot generally assume that indices are always known, it would probably better to store the whole `MatrixElementRef` element.

**Comment by AlexanderViand** [comment]
I'm assuming this is now dealt with differently in the CFGV since we've introduced the `Target` class?
