### ISSUE TITLE
Make tests less brittle w.r.t. function parameter evaluation order

### ISSUE THREAD

**Issue by AlexanderViand** [MarbleHE/ABC#19]
Because of the way that we define the ASTs for tests, e.g. "new If( <new expr>, <new block>, <new block>)", the order in which AST elements get created is unspecified. Since most tests rely on comparing Nodes' uniqueID which increments sequentially, this makes the tests very brittle.

The brute-force way of solving this would be to introduce new variables for each parameter, however this would make the code very hard to read. 

Instead, a cleaner solution would be to implement a parser that translates an AST from a text file into a C++ Ast object with deterministic initialisation order.

**Comment by pjattke** [comment]
This is also useful for tests that at the moment depend on the result of a visitor (e.g., see 20724c5ea1724b6d9c8c3894fc6410d24c124b2d) as every time the visitor is changed, also the test will break.

We could use the serialization/deserialization feature of the already integrated [nlohmann/json](https://github.com/nlohmann/json#serialization--deserialization) library to save and restore ASTs. Probably, this might require to extend the current JSON output by additional information, e.g., node IDs to describe the detailed state.

**Comment by AlexanderViand** [comment]
This has been addressed by the introduction of the parser
