### ISSUE TITLE
Omit rewriting of If-statement if condition is runtime-known and public 

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/ABC#4]
If-statements with conditions depending on runtime-known and public variables should not be rewritten because the runtime system can determine which branch must be executed. This is more efficient because rewriting would involve executing both branches (and involve additional condition checks before executing each statement). See TODO note in CompileTimeExpressionSimplifier class.

This extension depends on the implementation of scope-handling in the SecretTaintingVisitor (see #3), to determine if a variable—given as pair of variable identifier and scope where it is declared in—is public.

**Comment by AlexanderViand** [comment]
Handled in new rewriter
