### ISSUE TITLE
Add tests for evaluation of Arithmetic/LogicalExpr

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/ABC#6]
There are only very few tests for the evaluation logic of arithmetic expressions (ArithmeticExpr) and logical expressions (LogicalExpr). Even though exhaustive testing may not be required, it still would make sense to have at least a few tests for each operator involving different combinations of operand types. 

See the tests for the OperatorExpr (OperatorExprTest.cpp) for an example of how this could be done and documented.

**Comment by AlexanderViand** [comment]
These classes are no longer present in the new smart-pointer based AST
