### ISSUE TITLE
Remove AbstractNode::supportsCircuitMode

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/ABC#9]
The method `AbstractNode::supportsCircuitMode` is obsolete and its naming is confusing. Its initial intention was to provide a way to distinguish between AST nodes that use the `AbstractNode`'s children/parent vector and those that do not. As now _almost all_ AST nodes use the children vector to store its attributes, the method is not required anymore.

- [ ] Adapt `CallExternal`: Store attributes in `AbstractNode`'s children vector
- [ ] Check if any class still does not use the `children/parent` vectors to store its attributes
  - [ ] Check if any class does not overwrite the inherited method `AbstractNode::supportsCircuitMode`
  - [ ] Check if the overwrite of `AbstractNode::supportsCircuitMode` in any class returns `False`
  - [ ] Check and remove usages of `AbstractNode::supportsCircuitMode` 
- [ ] Remove the method `AbstractNode::supportsCircuitMode`

**Comment by AlexanderViand** [comment]
CircuitMode is no longer a concept in the new smart-pointer-based ast
